Repository samuelribaric/REMLA-Project, pull requests merged in 2024-05, with the labels that each got.

#1 fixed requirements.txt
  requirements.txt
Labels: bug, a1

#2 Increased Modularity, updated gitignore for venv, enabled weight saving/loading
  .gitignore
  main.py
  notebooks/phishing-detection-cnn.ipynb
  notebooks/phishing-detection-cnn_1.ipynb
  src/__pycache__/data_loader.cpython-310.pyc
  src/__pycache__/model.cpython-310.pyc
  src/data_loader.py
  src/model.py
  src/train.py
Labels: a1

#3 Pylint config
  .pylintrc
  README.md
  activity.md
  requirements.txt
Labels: enhancement, a1

#5 Creating Stages and Automation through DVC
  .dvc/.gitignore
  .dvc/config
  .dvcignore
  .gitignore
  docs/pipeline.md
  docs/setup.md
  dvc.lock
  dvc.yaml
  params.yaml
  poetry.lock
  pyproject.toml
  report.txt
  requirements.txt
  src/__pycache__/data_loader.cpython-310.pyc
  src/__pycache__/model.cpython-310.pyc
  src/__pycache__/model.cpython-312.pyc
  src/data_downloader.py
  src/data_loader.py
  src/data_split.py
  src/encode_labels.py
  src/model.py
  src/test.py
  src/test_model.py
  src/tokenize_features.py
  src/train.py
  src/train_model.py
Labels: a1

#15 Fixes pylint errors for pages
  .pylintrc
  src/data_downloader.py
  src/data_loader.py
  src/data_split.py
  src/encode_labels.py
  src/model.py
  src/test.py
  src/test_model.py
  src/tokenize_features.py
  src/train.py
  src/train_model.py
Labels: a1

#16 Poetry requirements
  .pylintrc
  README.md
  activity.md
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: a1
